import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Theme = "light" | "dark";
export type Lang = "en" | "es" | "fr" | "de" | "pt";

export const languages: { code: Lang; label: string }[] = [
  { code: "en", label: "English" },
  { code: "es", label: "Español" },
  { code: "fr", label: "Français" },
  { code: "de", label: "Deutsch" },
  { code: "pt", label: "Português" },
];

type Dict = Record<string, string>;

const en: Dict = {
  workspace: "Workspace",
  insight: "Insight",
  briefing: "Today's Briefing",
  calendar: "Unified Calendar",
  inbox: "Communication Inbox",
  timeline: "Client Timeline",
  contacts: "Contacts",
  reports: "Reports",
  automation: "Automation",
  search: "Search clients, meetings, messages…",
  language: "Language",
  lightMode: "Light mode",
  darkMode: "Dark mode",
  storage: "Storage",
  greeting: "Good morning, Maya",
  greetingSub: "You have {m} meetings, {c} missed calls and {a} priority actions on the board today.",
  reviewBoard: "Review Board",
  openCalendar: "Open Calendar",
  meetingsToday: "Meetings today",
  missedCalls: "Missed calls",
  openEmails: "Open emails",
  actionItems: "Action items",
  nextAt: "Next at",
  awaitingCallback: "2 awaiting callback",
  unreadFlagged: "5 unread · 2 flagged",
  dueBefore: "2 due before 2pm",
  todaysMeetings: "Today's Meetings",
  unifiedSchedule: "Unified schedule",
  events: "events",
  day: "Day",
  week: "Week",
  month: "Month",
  addMeeting: "+ Add Meeting",
  addCustomEvent: "+ Custom Event",
  priorityActions: "Priority Actions",
  open: "open",
  viewAll: "View all",
  email: "Email",
  whatsapp: "WhatsApp",
  smsCalls: "SMS / Calls",
  new: "new",
  title: "Title",
  date: "Date",
  time: "Time",
  duration: "Duration",
  tag: "Tag",
  color: "Color",
  notes: "Notes",
  cancel: "Cancel",
  save: "Save event",
  noneSelected: "Select a conversation",
  reply: "Reply",
  forward: "Forward",
  history: "Unified history",
  callNow: "Call",
  sendEmail: "Email",
  meeting: "Meeting",
  call: "Call",
};

const es: Dict = {
  ...en,
  workspace: "Espacio",
  insight: "Análisis",
  briefing: "Resumen de hoy",
  calendar: "Calendario unificado",
  inbox: "Bandeja de comunicación",
  timeline: "Historial de clientes",
  contacts: "Contactos",
  reports: "Informes",
  automation: "Automatización",
  search: "Buscar clientes, reuniones, mensajes…",
  language: "Idioma",
  lightMode: "Modo claro",
  darkMode: "Modo oscuro",
  storage: "Almacenamiento",
  greeting: "Buenos días, Maya",
  greetingSub: "Hoy tienes {m} reuniones, {c} llamadas perdidas y {a} acciones prioritarias.",
  reviewBoard: "Ver tablero",
  openCalendar: "Abrir calendario",
  meetingsToday: "Reuniones hoy",
  missedCalls: "Llamadas perdidas",
  openEmails: "Correos abiertos",
  actionItems: "Tareas",
  nextAt: "Próxima a las",
  todaysMeetings: "Reuniones de hoy",
  unifiedSchedule: "Agenda unificada",
  events: "eventos",
  day: "Día",
  week: "Semana",
  month: "Mes",
  addMeeting: "+ Añadir reunión",
  addCustomEvent: "+ Evento personalizado",
  priorityActions: "Acciones prioritarias",
  open: "abiertas",
  viewAll: "Ver todo",
  email: "Correo",
  smsCalls: "SMS / Llamadas",
  new: "nuevos",
  title: "Título",
  date: "Fecha",
  time: "Hora",
  duration: "Duración",
  tag: "Etiqueta",
  color: "Color",
  notes: "Notas",
  cancel: "Cancelar",
  save: "Guardar evento",
  noneSelected: "Selecciona una conversación",
  reply: "Responder",
  forward: "Reenviar",
  history: "Historial unificado",
  callNow: "Llamar",
  sendEmail: "Correo",
  meeting: "Reunión",
  call: "Llamada",
};

const fr: Dict = {
  ...en,
  workspace: "Espace",
  insight: "Analyse",
  briefing: "Briefing du jour",
  calendar: "Calendrier unifié",
  inbox: "Boîte de communication",
  timeline: "Historique client",
  contacts: "Contacts",
  reports: "Rapports",
  automation: "Automatisation",
  search: "Rechercher clients, réunions, messages…",
  language: "Langue",
  lightMode: "Mode clair",
  darkMode: "Mode sombre",
  storage: "Stockage",
  greeting: "Bonjour, Maya",
  greetingSub: "Vous avez {m} réunions, {c} appels manqués et {a} actions prioritaires aujourd'hui.",
  reviewBoard: "Voir le tableau",
  openCalendar: "Ouvrir le calendrier",
  meetingsToday: "Réunions aujourd'hui",
  missedCalls: "Appels manqués",
  openEmails: "E-mails ouverts",
  actionItems: "Actions",
  nextAt: "Prochaine à",
  todaysMeetings: "Réunions du jour",
  unifiedSchedule: "Agenda unifié",
  events: "événements",
  day: "Jour",
  week: "Semaine",
  month: "Mois",
  addMeeting: "+ Ajouter réunion",
  addCustomEvent: "+ Événement",
  priorityActions: "Actions prioritaires",
  open: "ouvertes",
  viewAll: "Tout voir",
  email: "E-mail",
  smsCalls: "SMS / Appels",
  new: "nouveaux",
  title: "Titre",
  date: "Date",
  time: "Heure",
  duration: "Durée",
  tag: "Étiquette",
  color: "Couleur",
  notes: "Notes",
  cancel: "Annuler",
  save: "Enregistrer",
  noneSelected: "Sélectionnez une conversation",
  reply: "Répondre",
  forward: "Transférer",
  history: "Historique unifié",
  callNow: "Appeler",
  sendEmail: "E-mail",
  meeting: "Réunion",
  call: "Appel",
};

const de: Dict = {
  ...en,
  workspace: "Arbeitsbereich",
  insight: "Auswertung",
  briefing: "Tagesbriefing",
  calendar: "Einheitlicher Kalender",
  inbox: "Kommunikations-Posteingang",
  timeline: "Kundenverlauf",
  contacts: "Kontakte",
  reports: "Berichte",
  automation: "Automatisierung",
  search: "Kunden, Termine, Nachrichten suchen…",
  language: "Sprache",
  lightMode: "Heller Modus",
  darkMode: "Dunkler Modus",
  storage: "Speicher",
  greeting: "Guten Morgen, Maya",
  greetingSub: "Heute: {m} Termine, {c} verpasste Anrufe und {a} Prioritäten.",
  reviewBoard: "Board öffnen",
  openCalendar: "Kalender öffnen",
  meetingsToday: "Termine heute",
  missedCalls: "Verpasste Anrufe",
  openEmails: "Offene E-Mails",
  actionItems: "Aufgaben",
  nextAt: "Nächster um",
  todaysMeetings: "Heutige Termine",
  unifiedSchedule: "Gesamtplan",
  events: "Termine",
  day: "Tag",
  week: "Woche",
  month: "Monat",
  addMeeting: "+ Termin",
  addCustomEvent: "+ Eigenes Ereignis",
  priorityActions: "Prioritäten",
  open: "offen",
  viewAll: "Alle ansehen",
  email: "E-Mail",
  smsCalls: "SMS / Anrufe",
  new: "neu",
  title: "Titel",
  date: "Datum",
  time: "Uhrzeit",
  duration: "Dauer",
  tag: "Kennzeichen",
  color: "Farbe",
  notes: "Notizen",
  cancel: "Abbrechen",
  save: "Speichern",
  noneSelected: "Konversation auswählen",
  reply: "Antworten",
  forward: "Weiterleiten",
  history: "Gesamter Verlauf",
  callNow: "Anrufen",
  sendEmail: "E-Mail",
  meeting: "Termin",
  call: "Anruf",
};

const pt: Dict = {
  ...en,
  workspace: "Área de trabalho",
  insight: "Análise",
  briefing: "Resumo de hoje",
  calendar: "Calendário unificado",
  inbox: "Caixa de comunicação",
  timeline: "Histórico do cliente",
  contacts: "Contactos",
  reports: "Relatórios",
  automation: "Automação",
  search: "Procurar clientes, reuniões, mensagens…",
  language: "Idioma",
  lightMode: "Modo claro",
  darkMode: "Modo escuro",
  storage: "Armazenamento",
  greeting: "Bom dia, Maya",
  greetingSub: "Hoje tem {m} reuniões, {c} chamadas perdidas e {a} ações prioritárias.",
  reviewBoard: "Ver quadro",
  openCalendar: "Abrir calendário",
  meetingsToday: "Reuniões hoje",
  missedCalls: "Chamadas perdidas",
  openEmails: "E-mails abertos",
  actionItems: "Tarefas",
  nextAt: "Próxima às",
  todaysMeetings: "Reuniões de hoje",
  unifiedSchedule: "Agenda unificada",
  events: "eventos",
  day: "Dia",
  week: "Semana",
  month: "Mês",
  addMeeting: "+ Adicionar reunião",
  addCustomEvent: "+ Evento personalizado",
  priorityActions: "Ações prioritárias",
  open: "abertas",
  viewAll: "Ver tudo",
  email: "E-mail",
  smsCalls: "SMS / Chamadas",
  new: "novos",
  title: "Título",
  date: "Data",
  time: "Hora",
  duration: "Duração",
  tag: "Etiqueta",
  color: "Cor",
  notes: "Notas",
  cancel: "Cancelar",
  save: "Guardar evento",
  noneSelected: "Selecione uma conversa",
  reply: "Responder",
  forward: "Reencaminhar",
  history: "Histórico unificado",
  callNow: "Ligar",
  sendEmail: "E-mail",
  meeting: "Reunião",
  call: "Chamada",
};

const dicts: Record<Lang, Dict> = { en, es, fr, de, pt };

type Ctx = {
  theme: Theme;
  setTheme: (t: Theme) => void;
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const SettingsContext = createContext<Ctx | null>(null);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>("light");
  const [lang, setLang] = useState<Lang>("en");

  useEffect(() => {
    const root = document.documentElement;
    root.classList.toggle("dark", theme === "dark");
  }, [theme]);

  const t = (key: string, vars?: Record<string, string | number>) => {
    let value = dicts[lang][key] ?? en[key] ?? key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) value = value.replace(`{${k}}`, String(v));
    }
    return value;
  };

  return (
    <SettingsContext.Provider value={{ theme, setTheme, lang, setLang, t }}>{children}</SettingsContext.Provider>
  );
}

export function useSettings() {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error("useSettings must be used inside SettingsProvider");
  return ctx;
}
